services:
  - type: web
    name: pharmacy-management-system
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: your_mysql_password
      - key: DB_NAME
        value: pharmacy
      - key: DB_PORT
        value: 3306
